# -*- coding: utf-8 -*-
"""기컴프 12주차 크롤링 팀과제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y0aacsd33eI71xF70oE7JMQfS7LI9qrt
"""

!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import time
from selenium import webdriver


options = webdriver.ChromeOptions()
options.add_argument('--headless')      
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver', options=options)

url = "https://www.moef.go.kr/id/asist.do?menuNo=3070100" 
driver.get(url)

org = []
sum = []

for i in range(1,15):
  name = driver.find_element_by_xpath(f'//*[@id="container"]/div[2]/section/div/table/tbody/tr[{i}]/th').text
  org.append(name)
  
  name1 = driver.find_element_by_xpath(f'//*[@id="container"]/div[2]/section/div/table/tbody/tr[{i}]/td[1]').text
  sum.append(name1)

print('--- 2019년 국고보조금 총괄 현황을 출력합니다. ---')
print('                                                    (단위: 백만원)')
for k in range(14):
  print(f'{org[k]}의 2019년 예산 소계는 {sum[k]}입니다.')
  print('')